### ISSUE TITLE
It doesn't override environment billingstack.endpoint

### ISSUE THREAD

**Issue by davidfergo** [stacksherpa/billingstack-ui-deprecated#4]
When you start the application with:

$>grails -Dbillingstack.endpoint=http://localhost:9191/billingstack run-app

The 'billingstack.endpoint' is not overrided in the application (fixed value in source code)

**Comment by woorea** [comment]
BillingStack UI config should be placed under /etc/billingstack/billingstack-ui.properties or use -Dbillingstack-ui.config.location
